
name: shift-left

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
   job_1:
    runs-on: ubuntu-latest
    name: My fisrt job
   job_2:
    runs-on: ubuntu-latest
    name: My second job
