
name: shift-left

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
   job_1:
    runs-on: ubuntu-latest
    name: install_dependencies
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
    
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
        
      - name: Build with Maven
        run: cd backend && mvn -B package --file pom.xml -DskipTests
   job_2:
    runs-on: ubuntu-latest
    name: tests
    steps:
      - name: Unit tests
        run: cd backend && mvn test
