
name: shift-left

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
   job_1:
    runs-on: ubuntu-latest
    name: install_dependencies
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
    
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
        
      - name: Build with Maven
        run: cd backend && mvn -B package --file pom.xml -DskipTests
   job_2:
    runs-on: ubuntu-latest
    name: unit
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        
      - name: Unit tests
        run: cd backend && mvn test
    needs: job_1
   job_3:
    runs-on: ubuntu-latest
    name: mutation
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        
      - name: Mutation tests
        run: cd backend && mvn test org.pitest:pitest-maven:mutationCoverage
    needs: job_1
   job_4:
    runs-on: ubuntu-latest
    name: arch
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        
      - name: Arch tests
        run: cd backend && echo "Arch tests execution"
    needs: job_1
    
   job_5:
     runs-on: ubuntu-latest
     name: reports
     steps:
      - name: Checkout project
        uses: actions/checkout@v3
        
      - name: Arch tests
        run: cd backend && echo "Reports"
     needs: [job_2,job_3,job_4]
